version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      non-major:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      non-major-security:
        applies-to: 'security-updates'
        patterns:
          - '*'
    ignore:
      # ithaka/pharos#856
      - dependency-name: 'react'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'react-dom'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/react'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/react-dom'
        update-types:
          - 'version-update:semver-major'
