version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      non-major:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      # ithaka/pharos#745
      - dependency-name: '@lit-labs/scoped-registry-mixin'
      - dependency-name: '@webcomponents/scoped-custom-element-registry'

      # ithaka/pharos#634
      - dependency-name: 'lit'
        update-types:
          - 'version-update:semver-major'

      # ithaka/pharos#780
      - dependency-name: 'style-dictionary'
        update-types:
          - 'version-update:semver-major'

      # Gatsby build currently failing, possibly fixed by doing ithaka/pharos#777
      - dependency-name: '@babel/core'
        update-types:
          - 'version-update:semver-patch'
