version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      non-major:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      # ithaka/pharos#780
      - dependency-name: 'style-dictionary'
        update-types:
          - 'version-update:semver-major'

      # ithaka/pharos#856
      - dependency-name: 'react'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'react-dom'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/react'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/react-dom'
        update-types:
          - 'version-update:semver-major'

      # ithaka/pharos#866
      - dependency-name: '@babel/core'
        update-types:
          - 'version-update:semver-patch'
          - 'version-update:semver-minor'
          - 'version-update:semver-major'
