const focusable = `
  a[href],
  area[href],
  button:not([disabled]),
  details,
  iframe,
  input:not([disabled]),
  select:not([disabled]),
  textarea:not([disabled]),
  [contentEditable="true"],
  [tabindex]:not([tabindex="-1"]),
  [data-pharos-component="PharosCheckbox"]:not([disabled]),
  [data-pharos-component="PharosRadioButton"]:not([disabled]),
  [data-pharos-component="PharosTextInput"]:not([disabled]),
  [data-pharos-component="PharosInputGroup"]:not([disabled]),
  [data-pharos-component="PharosSelect"]:not([disabled]),
  [data-pharos-component="PharosInputGroupSelect"]:not([disabled]),
  [data-pharos-component="PharosTextarea"]:not([disabled]),
  [data-pharos-component="PharosCombobox"]:not([disabled]),
  [data-pharos-component="PharosAlert"],
  [data-pharos-component="PharosDropdownMenuItem"]:not([disabled]),
  [data-pharos-component="PharosLink"][href],
  [data-pharos-component="PharosButton"]:not([disabled]),
  [data-pharos-component="PharosTab"],
  [data-pharos-component="PharosDropdownMenuNavLink"][href],
  [data-pharos-component="PharosSidenavLink"][href],
  [data-pharos-component="PharosToast"],
  [data-pharos-component="PharosBreadcrumbItem"][href],
  [data-pharos-component="PharosSidenavButton"]:not([disabled])
`;

export default focusable;
